name: Clean

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
    - name: Prettify code
      uses: creyD/prettier_action@v4.3
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write '**/*.{js,jsx,ts,tsx}'

  lint:
    runs-on: ubuntu-latest
    steps:

      - name: 'Create env file'
        uses: actions/checkout@v3
      
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Packages
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        uses: sibiraj-s/action-eslint@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # optional
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true
          ignore-path: .eslintignore
          # ignore-patterns:
